spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/2021new?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8 #url
    username: root  #用户名
    password: 1234  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
server:
  port: 8083
  servlet:
    context-path: /api  #项目名称 必须加上/ ,访问地址localhost:8088/api/具体接口地址
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.personal.yiboot.bean.pojo #配置实体类
  config-location: classpath:sqlmapconfig.xml #分页

#分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#swagger2
swagger:
  enable: true

#dubbo zk
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
#    scan:
#      base-packages: com.personal.yiboot.comsumer










